import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "../components/ui/dropdown-menu";
import SaveUser from '@/components/saveUser';
import {
  BriefcaseBusiness,
  BarChart3,
  MessageSquareCode,
  GraduationCap,
  ChevronDown,
  StarsIcon,
} from "lucide-react";
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import LenisProvider from '@/lib/LenisProvider';
import RouteLoader from '@/components/RouteLoader';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'SkillLens',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <LenisProvider>
      <RouteLoader />
      <ClerkProvider>
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            
            {/* Header */}
            <style>
        {`
          @keyframes spin-slow {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
          }
          .spin-slow {
            animation: spin-slow 6s linear infinite;
          }
        `}
      </style>
            <header className="fixed top-0 left-0 w-full z-50 backdrop-blur-md bg-transparent border-b border-white/10 shadow-sm">
              <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
                {/* Logo */}
                <Link href="/" className="text-white font-bold text-lg">SkillLens</Link>

                {/* Navigation */}
                <div className="flex items-center gap-3">
                  <SignedIn>
                    <SaveUser />
                    {/* Progress Button */}
                    <Link href="/progress">
                      <Button
                        variant="ghost"
                        className="hover:border-cyan-400 border border-transparent text-white transition-colors duration-200"
                      >
                        Track Progress
                      </Button>
                    </Link>

                    {/* Growth Tools Dropdown */}
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button
                          variant="ghost"
                          className="flex items-center gap-2 text-white hover:border-fuchsia-500 border border-transparent transition-colors"
                        >
                          <StarsIcon className="h-4 w-4 spin-slow" />
                          <span className="hidden md:block">Growth Tools</span>
                          <ChevronDown className="h-4 w-4" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end" className="w-56 bg-[#181926] text-white border border-white/10 shadow-xl">
                      
                      <DropdownMenuItem asChild>
                          <Link href="/roadmaps" className="flex items-center gap-2">
                            <BriefcaseBusiness className="h-4 w-4" />
                            <span>Career Roadmaps</span>
                          </Link>
                        </DropdownMenuItem>
                        
                      <DropdownMenuItem asChild>
                          <Link href="/insights" className="flex items-center gap-2">
                            <MessageSquareCode className="h-4 w-4" />
                            <span>Industry Insights</span>
                          </Link>
                        </DropdownMenuItem>
                       
                        <DropdownMenuItem asChild>
                          <Link href="/github-analysis" className="flex items-center gap-2">
                            <BarChart3 className="h-4 w-4" />
                            <span>GitHub Analysis</span>
                          </Link>
                        </DropdownMenuItem>
                        <DropdownMenuItem asChild>
                          <Link href="/interview" className="flex items-center gap-2">
                            <GraduationCap className="h-4 w-4" />
                            <span>Interview Prep</span>
                          </Link>
                        </DropdownMenuItem>
                        
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </SignedIn>

                  {/* Auth Buttons */}
                  <SignedOut>
                    <SignInButton>
                      <Button
                        variant="outline"
                        className="border-white/20 text-white hover:border-cyan-500 transition-colors"
                      >
                        Sign In
                      </Button>
                    </SignInButton>
                    <SignUpButton>
                      <Button className="bg-[#6c47ff] text-white hover:bg-[#7d5bff] transition-all">
                        Sign Up
                      </Button>
                    </SignUpButton>
                  </SignedOut>

                  {/* User Avatar */}
                  <SignedIn>
                    <UserButton
                      appearance={{
                        elements: {
                          avatarBox: "w-9 h-9",
                          userButtonPopoverCard: "shadow-xl",
                        },
                      }}
                      afterSignOutUrl="/"
                    />
                  </SignedIn>
                </div>
              </div>
            </header>

            {/* Page Content */}
            <div className="pt-16">{children}</div>

            {/* Footer */}
            <footer className="bg-black py-12">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Made with 💗 by Teja</p>
              </div>
            </footer>
          </body>
        </html>
      </ClerkProvider>
    </LenisProvider>
  )
}
